### ISSUE TITLE
TypeError: Cannot read property 'toFloat' of null

### ISSUE THREAD

**Issue by mimmi20** [WhichBrowser/Parser-JavaScript#15]
/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Analyser/Header/Useragent/Browser.js:1205
        if (this.data.os.name === 'Windows Phone' && this.data.os.version.toFloat() >= 8) {
                                                                          ^
TypeError: Cannot read property 'toFloat' of null
    at Useragent.detectUC (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Analyser/Header/Useragent/Browser.js:1205:75)
    at Useragent.detectBrowser (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Analyser/Header/Useragent/Browser.js:33:22)
    at new Useragent (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Analyser/Header/Useragent.js:15:27)
    at Analyser.analyseUserAgent (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Analyser/Header.js:74:5)
    at Analyser.analyseHeaders (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Analyser/Header.js:11:31)
    at Analyser.analyse (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Analyser.js:45:27)
    at Parser.analyse (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Parser.js:55:14)
    at new Parser (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/node_modules/which-browser/src/Parser.js:21:12)
    at Interface.<anonymous> (/home/developer/projects/useragent-parser-comparison/parsers/whichbrowser-js-0/parse:34:17)
    at Interface.emit (events.js:160:13)

**Comment by mariotsi** [comment]
Hi, thanks for reporting it. Can you provide the user agent used? Thanks

**Comment by mimmi20** [comment]
I'm not able to reproduce the error and to get the used useragent.

**Comment by mariotsi** [comment]
If you encounter this error anymore please reopen the issue. Thanks @mimmi20
